---
GENERAL:
  symbol: ["@", "@(", ")@"]
  bracket: ["[", "]"]
UTAGS:
  midasi:
    bcml: h3.bbb
  ruby:
    bcml: pre.[brush:ruby]
  python:
    bcml: pre.[brush:python]
  js:
    bcml: pre.[brush:js]
TAGS:
  h1:
  h2:
  h3:
  h4:
  h5:
  h6:
  a:
  span:
  div:
  pre:
    escape: true
STAGS:
  - mokuzi
QUALIFIERS:
  ".":
    point: intag
    usage: class="<qsub>"
  "#":
    point: intag
    usage: id="<qsub>"
  ":":
    point: outtag
    usage: [<a href="<qsub>">, </a>]
    other:
    - bracket
