---
GENERAL:
  symbol: ["@", "@(", ")@"]
  bracket: ["[", "]"]
  comment: ["@---","---@"]
USERTAGS:
  midasi:
    bcml: h3.bbb
  ruby:
    bcml: pre.[brush:ruby]
  python:
    bcml: pre.[brush:python]
  html:
    bcml: pre.[brush:html]
  js:
    bcml: pre.[brush:js]
  bash:
    bcml: pre.[brush:bash]
  yaml:
    bcml: pre.[brush:yaml]
  plain:
    bcml: pre.[brush:plain]
  command:
    bcml: code.command
TAGS:
  h1:
    display: block
  h2:
    display: block
  h3:
    display: block
  h4:
    display: block
  h5:
    display: block
  h6:
    display: block
  a:
    display: inline
  div:
    display: block
  span:
    display: inline
  p:
    display: block
  pre:
    display: block
    escape: true
  ul:
    display: block
  li:
    display: inline
  b:
    display: inline
  i:
    display: inline
  code:
    display: block
  blockquote:
    display: block
QUALIFIERS:
  ".":
    point: intag
    usage: class="<qsub>"
  "#":
    point: intag
    usage: id="<qsub>"
  ":":
    point: outtag
    usage: [<a href="<qsub>">, </a>]
SPECIALTAGS:
  - mokuzi
  - ":"
